### ISSUE TITLE
Can't tar Codescape-Bare-Metal.tar.gz , file Damaged ? 

### ISSUE THREAD

**Issue by fwengineer** [prplfoundation/prpl-hypervisor#9]
in prpl-hypervisor/bin/install-tools-pic32mz.sh:

# wget -O Codescape-Bare-Metal.tar.gz https://community.imgtec.com/?do-download=linux-x64-mti-bare-metal-2016-05-03

‘Codescape-Bare-Metal.tar.gz’ saved [87145]

# tar -zxvf Codescape-Bare-Metal.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

File's size is 87145 bytes , File Damaged ???

**Comment by crmoratelli** [comment]
Hi,

They moved the files, you can download the toolchain from this link:

https://www.mips.com/?do-download=linux-x64-img-bare-metal-2016-05-03

I will update the install script soon.

Thank  you.

**Comment by fwengineer** [comment]
Thank you.
I downloaded

URL_MPLABIPE=http://ww1.microchip.com/downloads/en/DeviceDoc/MPLABX-v4.05-linux-installer.tar
URL_CODESCAPE=https://www.mips.com/?do-download=linux-x64-mti-bare-metal-2016-05-06

It work fine.

**Comment by crmoratelli** [comment]
Thanks, I updated the install script with your URLs.

Let me know if you have any other problem.
